### ISSUE TITLE
Fall Animation

### ISSUE THREAD

**Issue by Wixonic** [Lunairia/Donut#13]
- [x] : Add a **Fall Animation**

```css
@keyframes fall
{
	0% {transform: translateY(-100px);}
	8% {transform: translateY(-98px);}
	12% {transform: translateY(-95px);}
	15% {transform: translateY(-91px);}
	19% {transform: translateY(-86px);}
	23% {transform: translateY(-80px);}
	26% {transform: translateY(-73px);}
	30% {transform: translateY(-65px);}
	34% {transform: translateY(-56px);}
	37% {transform: translateY(-46px);}
	41% {transform: translateY(-35px);}
	45% {transform: translateY(-23px);}
	48% {transform: translateY(-10px);}
	52% {transform: translateY(4px);}
	56% {transform: translateY(19px);}
	59% {transform: translateY(35px);}
	63% {transform: translateY(52px);}
	67% {transform: translateY(70px);}
	70% {transform: translateY(90px);}
	85% {transform: translateY(100px) scale(1.1,0.7);}
	100% {transform: translateY(100px) scale(1.3,0.3);}
}
```

__Originally posted by @Wixonic in https://github.com/Lunairia/Donut/issues/11#issuecomment-756333199__
